label v11check:
    $ chikapoint = 0
    $ chikamiss = 0
    $ yumipoint = 0
    $ ayanepoint = 0
    $ ayanemiss = 0
    $ sanapoint = 0
    $ makotopoint = 0
    $ mikupoint = 0
    $ rinpoint = 0
    $ rinmiss = 0
    $ futabapoint = 0
    $ futabamiss = 0
    $ amipoint = 0
    $ amimiss = 0
    $ mayapoint = 0
    $ mollypoint = 0
    $ tsuneyopoint = 0
    $ sarapoint = 0
    $ saramiss = 0
    $ harukapoint = 0
    $ harukamiss = 0
    $ makipoint = 0
    $ kaoripoint = 0
    $ karinpoint = 0
    $ kirinpoint = 0
    $ chinamipoint = 0
    $ chap1point = 0
    $ happypoint = 0
    $ happymiss = 0
    $ chap2point = 0

    #CHAPTER 1 (X NON-MISSABLE)
    if everyday == True:
        $ chap1point += 1
    if clichebath == True:
        $ chap1point += 1
    if amiawake == True:
        $ chap1point += 1
    if firstclass == True:
        $ chap1point += 1
    if sleepover == True:
        $ chap1point += 1
    if day5 == True:
        $ chap1point += 1
    if day7 == True:
        $ chap1point += 1
    if day8 == True:
        $ chap1point += 1
    if day12 == True:
        $ chap1point += 1
    if day14 == True:
        $ chap1point += 1
    if day16 == True:
        $ chap1point += 1
    if day20 == True:
        $ chap1point += 1
    if day21 == True:
        $ chap1point += 1
    if day24 == True:
        $ chap1point += 1
    if day26 == True:
        $ chap1point += 1
    if day28 == True:
        $ chap1point += 1
    if day30 == True:
        $ chap1point += 1
    if day33 == True:
        $ chap1point += 1
    if day34 == True:
        $ chap1point += 1
    if day36 == True:
        $ chap1point += 1
    if day38 == True:
        $ chap1point += 1
    if day40 == True:
        $ chap1point += 1
    if day42 == True:
        $ chap1point += 1
    if day44 == True:
        $ chap1point += 1
    if day48 == True:
        $ chap1point += 1
    if day50 == True:
        $ chap1point += 1
    if day54 == True:
        $ chap1point += 1
    if day56 == True:
        $ chap1point += 1
    if day60 == True:
        $ chap1point += 1
    if day63 == True:
        $ chap1point += 1
    if day65 == True:
        $ chap1point += 1
    if day70 == True:
        $ chap1point += 1
    if day72 == True:
        $ chap1point += 1
    if day77 == True:
        $ chap1point += 1
    if day79 == True:
        $ chap1point += 1
    if day80 == True:
        $ chap1point += 1
    if day83 == True:
        $ chap1point += 1
    if day85 == True:
        $ chap1point += 1
    if day89 == True:
        $ chap1point += 1
    if day91 == True:
        $ chap1point += 1
    if day96 == True:
        $ chap1point += 1
    if day102 == True:
        $ chap1point += 1
    if day103 == True:
        $ chap1point += 1
    if day110 == True:
        $ chap1point += 1
    if day114 == True:
        $ chap1point += 1
    if day120 == True:
        $ chap1point += 1
    if day121 == True:
        $ chap1point += 1
    if day126 == True:
        $ chap1point += 1
    if day128 == True:
        $ chap1point += 1
    if day130 == True:
        $ chap1point += 1
    if day138 == True:
        $ chap1point += 1
    if day140 == True:
        $ chap1point += 1
    if day142 == True:
        $ chap1point += 1
    if day144 == True:
        $ chap1point += 1
    if day150 == True:
        $ chap1point += 1
    if day153 == True:
        $ chap1point += 1
    if day154 == True:
        $ chap1point += 1
    if beachvacation1 == True:
        $ chap1point += 1
    if beachvacation2 == True:
        $ chap1point += 1
    if beachvacation3 == True:
        $ chap1point += 1
    if beachvacation4 == True:
        $ chap1point += 1
    if beachvacation5 == True:
        $ chap1point += 1
    if beachvacation6 == True:
        $ chap1point += 1
    if beachvacation7 == True:
        $ chap1point += 1
    if beachvacation8 == True:
        $ chap1point += 1
    if beachvacation9 == True:
        $ chap1point += 1
    if beachvacation10 == True:
        $ chap1point += 1
    if beachvacation11 == True:
        $ chap1point += 1
    if beachvacation12 == True:
        $ chap1point += 1
    if beachvacation13 == True:
        $ chap1point += 1
    if beachvacation14 == True:
        $ chap1point += 1
    if beachvacation15 == True:
        $ chap1point += 1
    if beachvacation16 == True:
        $ chap1point += 1
    if halloween1 == True:
        $ chap1point += 1
    if halloween2 == True:
        $ chap1point += 1
    if halloween3 == True:
        $ chap1point += 1
    if halloween4 == True:
        $ chap1point += 1
    if halloween5 == True:
        $ chap1point += 1
    if halloween6 == True:
        $ chap1point += 1
    if halloween7 == True:
        $ chap1point += 1
    if halloween8 == True:
        $ chap1point += 1
    if halloween9 == True:
        $ chap1point += 1
    if halloween10 == True:
        $ chap1point += 1
    if halloween11 == True:
        $ chap1point += 1
    if halloween12 == True:
        $ chap1point += 1
    if halloween13 == True:
        $ chap1point += 1
    if halloween14 == True:
        $ chap1point += 1
    if day214 == True:
        $ chap1point += 1
    if day215 == True:
        $ chap1point += 1
    if day216 == True:
        $ chap1point += 1
    if day217 == True:
        $ chap1point += 1
    if day218 == True:
        $ chap1point += 1
    if day220 == True:
        $ chap1point += 1
    if hoorayanotherreset == True:
        $ chap1point += 1

    #CHAPTER 2 ()
    if christmas1 == True:
        $ chap2point += 1
    if christmas2 == True:
        $ chap2point += 1
    if christmas3 == True:
        $ chap2point += 1
    if christmas4 == True:
        $ chap2point += 1
    if christmas5 == True:
        $ chap2point += 1
    if christmas6 == True:
        $ chap2point += 1
    if christmas7 == True:
        $ chap2point += 1

    #HAPPY (8 NON-MISSABLE/3 MISSABLE)
    if roomwithtrack == True:
        $ happypoint += 1
    if letterttrack == True:
        $ happypoint += 1
    if swimmingtrack == True:
        $ happypoint += 1
    elif amidorm10 == True and amifingered == False:
        $ happymiss += 1
    if howifeeltrack == True:
        $ happypoint += 1
    if connecttrack == True:
        $ happypoint += 1
    elif day103 == True and connecttrack == False:
        $ happymiss += 1
    if specialclassroomtrack == True:
        $ happypoint += 1
    elif amisroom15 == True and amifingered == False:
        $ happymiss += 1
    if ticktocktrack == True:
        $ happypoint += 1
    if trinity1track == True:
        $ happypoint += 1
    if trinity2track == True:
        $ happypoint += 1
    if trinity3track == True:
        $ happypoint += 1
    if babyfinches == True:
        $ happypoint += 1


    #CHIKA (13 NON-MISSABLE/1 MISSABLE)
    if firsttimemall == True:
        $ chikapoint += 1
    if chikafirsthall == True:
        $ chikapoint += 1
    if mall5 == True:
        $ chikapoint += 1
    if chikadorm5 == True:
        $ chikapoint += 1
    if mall10 == True:
        $ chikapoint += 1
    if chikadorm10 == True:
        $ chikapoint += 1
    if chikadorm15 == True:
        $ chikapoint += 1
    if mall15 == True:
        $ chikapoint += 1
    if chikadorm20 == True:
        $ chikapoint += 1
    if mall20 == True:
        $ chikapoint += 1
    if day139 == True:
        $ chikapoint += 1
    if chikainvite1 == True:
        $ chikapoint += 1
    if chikainvite2 == True:
        $ chikapoint += 1
    if chikalust10 == True:
        $ chikapoint += 1
    if chikalust10miss == True:
        $ chikamiss += 1

    #YUMI (12 NON-MISSABLE)
    if firsttimestreets == True:
        $ yumipoint += 1
    if yumifirsthall == True:
        $ yumipoint += 1
    if streets5 == True:
        $ yumipoint += 1
    if streets10 == True:
        $ yumipoint += 1
    if yumidorm5 == True:
        $ yumipoint += 1
    if yumidorm10 == True:
        $ yumipoint += 1
    if yumidorm15 == True:
        $ yumipoint += 1
    if streets15 == True:
        $ yumipoint += 1
    if streets20 == True:
        $ yumipoint += 1
    if yumidorm20 == True:
        $ yumipoint += 1
    if streets25 == True:
        $ yumipoint += 1
    if yumidorm25 == True:
        $ yumipoint += 1

    #AYANE (15 NON-MISSABLE/1 MISSABLE)
    if firsttimedojo == True:
        $ ayanepoint += 1
    if ayanefirsthall == True:
        $ ayanepoint += 1
    if dojo5 == True:
        $ ayanepoint += 1
    if dojo10 == True:
        $ ayanepoint += 1
    if ayanedorm5 == True:
        $ ayanepoint += 1
    if ayanedorm10 == True:
        $ ayanepoint += 1
    if dojo15 == True:
        $ ayanepoint += 1
    if ayanedorm15 == True:
        $ ayanepoint += 1
    if day68 == True:
        $ ayanepoint += 1
    if dojo20 == True:
        $ ayanepoint += 1
    if ayanedorm20 == True:
        $ ayanepoint += 1
    if ayanelust10 == True:
        $ ayanepoint += 1
    elif beachvacation14 == True and ayanelust10 == False:
        $ ayanemiss += 1
    if dojo25 == True:
        $ ayanepoint += 1
    if ayanedorm25 == True:
        $ ayanepoint += 1
    if dojo30 == True:
        $ ayanepoint += 1
    if ayanedorm30 == True:
        $ ayanepoint += 1

    #SANA (14 NON-MISSABLE)
    if firsttimebar == True:
        $ sanapoint += 1
    if sanafirsthall == True:
        $ sanapoint += 1
    if bar5 == True:
        $ sanapoint += 1
    if sanadorm5 == True:
        $ sanapoint += 1
    if bar10 == True:
        $ sanapoint += 1
    if sanadorm10 == True:
        $ sanapoint += 1
    if bar15 == True:
        $ sanapoint += 1
    if sanadorm15 == True:
        $ sanapoint += 1
    if bar20 == True:
        $ sanapoint += 1
    if sanadorm20 == True:
        $ sanapoint += 1
    if bar25 == True:
        $ sanapoint += 1
    if sanadorm25 == True:
        $ sanapoint += 1
    if bar30 == True:
        $ sanapoint += 1
    if sanadorm30 == True:
        $ sanapoint += 1

    #MAKOTO (15 NON-MISSABLE)
    if firsttimepornshop == True:
        $ makotopoint += 1
    if makotofirsthall == True:
        $ makotopoint += 1
    if pornshop5 == True:
        $ makotopoint += 1
    if makotodorm5 == True:
        $ makotopoint += 1
    if pornshop10 == True:
        $ makotopoint += 1
    if makotodorm10 == True:
        $ makotopoint += 1
    if pornshop15 == True:
        $ makotopoint += 1
    if makotodorm15 == True:
        $ makotopoint += 1
    if makotolust5 == True:
        $ makotopoint += 1
    if makotoinvite1 == True:
        $ makotopoint += 1
    if makotoinvite2 == True:
        $ makotopoint += 1
    if pornshop20 == True:
        $ makotopoint += 1
    if makotodorm20 == True:
        $ makotopoint += 1
    if pornshop25 == True:
        $ makotopoint += 1
    if makotodorm25 == True:
        $ makotopoint += 1

    #MIKU (13 NON-MISSABLE)
    if firsttimesoccerfield == True:
        $ mikupoint += 1
    if mikufirsthall == True:
        $ mikupoint += 1
    if soccer5 == True:
        $ mikupoint += 1
    if mikudorm5 == True:
        $ mikupoint += 1
    if soccer10 == True:
        $ mikupoint += 1
    if mikudorm10 == True:
        $ mikupoint += 1
    if soccer15 == True:
        $ mikupoint += 1
    if mikudorm15 == True:
        $ mikupoint += 1
    if soccer20 == True:
        $ mikupoint += 1
    if soccer25 == True:
        $ mikupoint += 1
    if mikudorm25 == True:
        $ mikupoint += 1
    if soccer30 == True:
        $ mikupoint += 1
    if mikudorm30 == True:
        $ mikupoint += 1

    #RIN (15 NON-MISSABLE/1 MISSABLE)
    if firsttimecafe == True:
        $ rinpoint += 1
    if cafesugar == True:
        $ rinpoint += 1
    if cafe10 == True:
        $ rinpoint += 1
    if rinfirsthall == True:
        $ rinpoint += 1
    if rinfirstvisit == True:
        $ rinpoint += 1
    if rindorm10 == True:
        $ rinpoint += 1
    if cafe15 == True:
        $ rinpoint += 1
    if rindorm15 == True:
        $ rinpoint += 1
    if cafe20 == True:
        $ rinpoint += 1
    if rindorm20 == True:
        $ rinpoint += 1
    if cafe25 == True:
        $ rinpoint += 1
    if rindorm25 == True:
        $ rinpoint += 1
    if cafe30 == True:
        $ rinpoint += 1
    if rindorm30 == True:
        $ rinpoint += 1
    if rindorm35 == True:
        $ rinpoint += 1
    if cafe35 == True:
        $ rinpoint += 1
    elif rindorm35 == True and rininvite == False:
        $ rinmiss += 1

    #FUTABA (16 NON-MISSABLE/2 MISSABLE)
    if firsttimelibrary == True:
        $ futabapoint += 1
    if futabafall == True:
        $ futabapoint += 1
    if library10 == True:
        $ futabapoint += 1
    if futabafirsthall == True:
        $ futabapoint += 1
    if futabafirstvisit == True:
        $ futabapoint += 1
    if futabadorm10 == True:
        $ futabapoint += 1
    if library15 == True:
        $ futabapoint += 1
    if futabadorm15 == True:
        $ futabapoint += 1
    if library20 == True:
        $ futabapoint += 1
    if futabadorm20 == True:
        $ futabapoint += 1
    if library25 == True:
        $ futabapoint += 1
    if futabadorm25 == True:
        $ futabapoint += 1
    elif library25 == True and bookdate == False:
        $ futabamiss += 1
    if day86 == True:
        $ futabapoint += 1
    if library30 == True:
        $ futabapoint += 1
    if futabadorm30 == True:
        $ futabapoint += 1
    if library35 == True:
        $ futabapoint += 1
    if futabadorm35 == True:
        $ futabapoint += 1
    if futabalust10 == True:
        $ futabapoint += 1
    if futabalust10miss == True:
        $ futabamiss += 1

    #AMI (11 NON-MISSABLE/3 MISSABLE)
    if firsttimeamisroom == True:
        $ amipoint += 1
    if amifirsthall == True:
        $ amipoint += 1
    if amisroom5 == True:
        $ amipoint += 1
    if amidorm5 == True:
        $ amipoint += 1
    if amisroom10 == True:
        $ amipoint += 1
    if amidorm10 == True:
        $ amipoint += 1
    if day98 == True:
        $ amipoint += 1
    elif amidorm10 == True and amifingered == False:
        $ amimiss += 1
    if amidorm15 == True:
        $ amipoint += 1
    if amisroom15 == True:
        $ amipoint += 1
    if amilust10 == True:
        $ amipoint += 1
    elif beachvacation16 == True and amilust10 == False:
        $ amimiss += 1
    if amisroom20 == True:
        $ amipoint += 1
    if amidorm20 == True:
        $ amipoint += 1
    if amisroom25 == True:
        $ amipoint += 1
    elif amidorm20 == True and amifingered == False:
        $ amimiss += 1
    if amidorm25 == True:
        $ amipoint += 1

    #MAYA (12 NON-MISSABLE)
    if firsttimeshrine == True:
        $ mayapoint += 1
    if mayafirsthall == True:
        $ mayapoint += 1
    if shrine5 == True:
        $ mayapoint += 1
    if mayadorm5 == True:
        $ mayapoint += 1
    if shrine10 == True:
        $ mayapoint += 1
    if mayadorm10 == True:
        $ mayapoint += 1
    if shrine15 == True:
        $ mayapoint += 1
    if mayadorm15 == True:
        $ mayapoint += 1
    if shrine20 == True:
        $ mayapoint += 1
    if mayadorm20 == True:
        $ mayapoint += 1
    if shrine25 == True:
        $ mayapoint += 1
    if mayadorm25 == True:
        $ mayapoint += 1

    #MOLLY (6 NON-MISSABLE)
    if mollycafe1 == True:
        $ mollypoint += 1
    if mollycafe5 == True:
        $ mollypoint += 1
    if mollycafe10 == True:
        $ mollypoint += 1
    if mollydorm5 == True:
        $ mollypoint += 1
    if mollydorm10 == True:
        $ mollypoint += 1
    if mollyfirsthall == True:
        $ mollypoint += 1

    #TSUNEYO (6 NON-MISSABLE)
    if ramen1 == True:
        $ tsuneyopoint += 1
    if ramen5 == True:
        $ tsuneyopoint += 1
    if ramen10 == True:
        $ tsuneyopoint += 1
    if tsuneyodorm5 == True:
        $ tsuneyopoint += 1
    if tsuneyodorm10 == True:
        $ tsuneyopoint += 1
    if tsuneyofirsthall == True:
        $ tsuneyopoint += 1

    #SARA (3 NON-MISSABLE/2 MISSABLE)
    if saradate1 == True:
        $ sarapoint += 1
    if saralust5 == True:
        $ sarapoint += 1
    elif bar15 == True and sarasex == False:
        $ saramiss += 1
    if sarainvite1 == True:
        $ sarapoint += 1
    if sarainvite2 == True:
        $ sarapoint += 1
    if saralust10 == True:
        $ sarapoint += 1
    elif halloween8 == True and saralust10 == False:
        $ saramiss += 1

    #HARUKA (4 NON-MISSABLE/2 MISSABLE)
    if harukadate1 == True:
        $ harukapoint += 1
    if harukadate5 == True:
        $ harukapoint += 1
    if harukafirstlust == True:
        $ harukapoint += 1
    elif harukadate5 == True and harukasex == False:
        $ harukamiss += 1
    if harukalust10 == True:
        $ harukapoint += 1
    elif halloween14 == True and harukalust10 == False:
        $ harukamiss += 1
    if harukadate10 == True:
        $ harukapoint += 1
    if harukadate15 == True:
        $ harukapoint += 1

    #MAKI (2 NON-MISSABLE)
    if makidate1 == True:
        $ makipoint += 1
    if makidate5 == True:
        $ makipoint += 1

    #KAORI (3 NON-MISSABLE)
    if kaoridate1 == True:
        $ kaoripoint += 1
    if kaoridate5 == True:
        $ kaoripoint += 1
    if kaoridate10 == True:
        $ kaoripoint += 1

    #KARIN (3 NON-MISSABLE)
    if karindate1 == True:
        $ karinpoint += 1
    if karindate5 == True:
        $ karinpoint += 1
    if karindate10 == True:
        $ karinpoint += 1

    #KIRIN (3 NON-MISSABLE)
    if kirindate1 == True:
        $ kirinpoint += 1
    if kirindate5 == True:
        $ kirinpoint += 1
    if kirindate10 == True:
        $ kirinpoint += 1

    #CHINAMI (2 NON-MISSABLE)
    if chinamidate1 == True:
        $ chinamipoint += 1
    if chinamidate5 == True:
        $ chinamipoint += 1

    return
